import { Clock, Zap, Sparkles, Building2, Star, Crown, Briefcase, Rocket, Infinity } from "lucide-react";
import type { Plan, PlanType } from "@/model/Plan";

export const PLANS: Plan[] = [
  {
    type: "TRIAL",
    name: "Trial",
    price: 0,
    trialDays: 14,
    description: "Full access for 14 days — no credit card required",
    features: [
      "14-day free trial",
      "50 scheduled posts",
      "5 connected accounts",
      "All post types (image, video, text)",
      "Priority support",
    ],
    limits: {
      scheduledPostsPerMonth: 50,
      connectedAccounts: 5,
      teamMembers: 3,
    },
  },
  {
    type: "BASE",
    name: "Base",
    price: 15,
    description: "For individuals getting started",
    stripePriceId: "price_todo_base_monthly",
    features: [
      "500 scheduled posts / month",
      "30 connected accounts",
      "All post types (image, video, text)",
      "Email support",
    ],
    limits: {
      scheduledPostsPerMonth: 500,
      connectedAccounts: 25,
      teamMembers: 1,
    },
  },
  {
    type: "PRO",
    name: "Pro",
    price: 25,
    description: "For creators growing their audience",
    popular: true,
    stripePriceId: "price_todo_pro_monthly",
    features: [
      "2000 scheduled posts / month",
      "100 connected accounts",
      "Advanced analytics",
      "Image, video & text posts",
      "Priority support",
    ],
    limits: {
      scheduledPostsPerMonth: 2000,
      connectedAccounts: 100,
      teamMembers: 5,
    },
  },
  {
    type: "ENTERPRISE",
    name: "Enterprise",
    price: 1000,
    customPricing: true,
    description: "For teams managing multiple brands",
    stripePriceId: "price_todo_enterprise_monthly",
    features: [
      "Unlimited scheduled posts",
      "Unlimited connected accounts",
      "Advanced analytics",
      "All post types",
      "Dedicated support",
      "Custom branding",
    ],
    limits: {
      scheduledPostsPerMonth: "Unlimited",
      connectedAccounts: "Unlimited",
      teamMembers: "Unlimited",
    },
  },
  // ─── Influencer plans ────────────────────────────────────────────────────────
  {
    type: "INFLUENCER_BASE",
    name: "Influencer Base",
    price: 12,
    description: "For creators building their presence",
    stripePriceId: "price_todo_influencer_base_monthly",
    features: [
      "100 scheduled posts / month",
      "5 connected accounts",
      "1 workspace (main)",
      "All post types (image, video, text)",
      "Email support",
    ],
    limits: {
      scheduledPostsPerMonth: 100,
      connectedAccounts: 5,
      teamMembers: 1,
    },
  },
  {
    type: "INFLUENCER_PRO",
    name: "Influencer Pro",
    price: 29,
    description: "For serious creators scaling their brand",
    popular: true,
    stripePriceId: "price_todo_influencer_pro_monthly",
    features: [
      "500 scheduled posts / month",
      "15 connected accounts",
      "1 workspace (main)",
      "Advanced analytics",
      "Priority support",
    ],
    limits: {
      scheduledPostsPerMonth: 500,
      connectedAccounts: 15,
      teamMembers: 1,
    },
  },
  // ─── Agency plans ────────────────────────────────────────────────────────────
  {
    type: "AGENCY_BASE",
    name: "Agency Base",
    price: 79,
    description: "For small agencies managing client brands",
    stripePriceId: "price_todo_agency_base_monthly",
    features: [
      "Up to 3 workspaces",
      "300 posts / month per workspace",
      "10 accounts per workspace",
      "Team members (unlimited seats)",
      "Email support",
    ],
    limits: {
      scheduledPostsPerMonth: 300,
      connectedAccounts: 10,
      teamMembers: "Unlimited",
    },
  },
  {
    type: "AGENCY_PRO",
    name: "Agency Pro",
    price: 199,
    description: "For growing agencies with multiple clients",
    popular: true,
    stripePriceId: "price_todo_agency_pro_monthly",
    features: [
      "Up to 10 workspaces",
      "1000 posts / month per workspace",
      "30 accounts per workspace",
      "Team members (unlimited seats)",
      "Priority support",
    ],
    limits: {
      scheduledPostsPerMonth: 1000,
      connectedAccounts: 30,
      teamMembers: "Unlimited",
    },
  },
  {
    type: "AGENCY_CUSTOM",
    name: "Agency Custom",
    price: 0,
    customPricing: true,
    description: "Tailored for enterprise agencies",
    features: [
      "Unlimited workspaces",
      "Unlimited posts per workspace",
      "Unlimited connected accounts",
      "Dedicated account manager",
      "Custom SLA & onboarding",
    ],
    limits: {
      scheduledPostsPerMonth: "Unlimited",
      connectedAccounts: "Unlimited",
      teamMembers: "Unlimited",
    },
  },
];

export const PLAN_ICONS: Record<PlanType, React.ElementType> = {
  TRIAL:           Clock,
  BASE:            Zap,
  PRO:             Sparkles,
  ENTERPRISE:      Building2,
  INFLUENCER_BASE: Star,
  INFLUENCER_PRO:  Crown,
  AGENCY_BASE:     Briefcase,
  AGENCY_PRO:      Rocket,
  AGENCY_CUSTOM:   Infinity,
};
