export const authClerkAppearance = {
  variables: {
    colorPrimary: "var(--primary-color)",
    colorPrimaryForeground: "#ffffff",
    colorDanger: "var(--negative-color)",
    colorSuccess: "var(--positive-color)",
    colorWarning: "var(--warning-color)",
    colorNeutral: "var(--primary-text-color)",
    colorForeground: "var(--primary-text-color)",
    colorMutedForeground: "var(--secondary-text-color)",
    colorBackground: "var(--primary-background-color)",
    colorInputForeground: "var(--primary-text-color)",
    colorInput: "var(--secondary-background-color)",
    colorBorder: "var(--ui-border-color)",
    colorRing: "var(--primary-color)",
    colorShadow: "rgba(0, 0, 0, 0)",
    fontFamily: "var(--font-vibe-sans), ui-sans-serif, system-ui, sans-serif",
    fontFamilyButtons: "var(--font-vibe-sans), ui-sans-serif, system-ui, sans-serif",
    fontSize: "0.875rem",
    borderRadius: "0.5rem",
    spacing: "1rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full",
    card:
      "w-full rounded-[1.25rem] border border-[var(--ui-border-color)] bg-[var(--primary-background-color)] shadow-[0_1.125rem_3rem_rgba(41,47,76,0.12)] dark:shadow-[0_1.5rem_3rem_rgba(0,0,0,0.35)]",
    headerTitle: "text-heading-20 text-[var(--primary-text-color)]",
    headerSubtitle: "text-copy-14 text-[var(--secondary-text-color)]",
    socialButtonsBlockButton:
      "h-10 rounded-md border border-[var(--ui-border-color)] bg-[var(--primary-background-color)] text-label-14 text-[var(--primary-text-color)] shadow-none transition-colors hover:border-[var(--primary-text-color)] hover:bg-[var(--primary-background-hover-color)] focus-visible:ring-2 focus-visible:ring-[var(--primary-color)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--primary-background-color)]",
    socialButtonsBlockButtonText: "text-label-14 text-[var(--primary-text-color)]",
    socialButtonsProviderIcon: "text-[var(--secondary-text-color)]",
    dividerText: "text-label-12 uppercase tracking-[0.14em] text-[var(--secondary-text-color)]",
    dividerLine: "bg-[var(--layout-border-color)]",
    formFieldLabel: "text-label-14 text-[var(--primary-text-color)]",
    formFieldInput:
      "h-10 rounded-md border border-[var(--ui-border-color)] bg-[var(--secondary-background-color)] px-3 text-copy-14 text-[var(--primary-text-color)] shadow-none placeholder:text-[var(--placeholder-color)] focus:border-[var(--primary-color)] focus-visible:ring-2 focus-visible:ring-[var(--primary-color)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--primary-background-color)]",
    formFieldInputShowPasswordButton:
      "text-[var(--secondary-text-color)] transition-colors hover:text-[var(--primary-text-color)]",
    formButtonPrimary:
      "h-10 rounded-md bg-[var(--primary-color)] text-label-14 text-white shadow-none transition-colors hover:bg-[var(--primary-hover-color)] focus-visible:ring-2 focus-visible:ring-[var(--primary-color)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--primary-background-color)]",
    formFieldAction: "text-label-13 text-[var(--primary-color)] hover:text-[var(--primary-hover-color)]",
    formFieldErrorText: "text-copy-13 text-[var(--negative-color)]",
    formFieldSuccessText: "text-copy-13 text-[var(--positive-color)]",
    formResendCodeLink: "text-label-13 text-[var(--primary-color)] hover:text-[var(--primary-hover-color)]",
    otpCodeFieldInput:
      "rounded-md border border-[var(--ui-border-color)] bg-[var(--secondary-background-color)] text-label-14 text-[var(--primary-text-color)] shadow-none focus:border-[var(--primary-color)] focus-visible:ring-2 focus-visible:ring-[var(--primary-color)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--primary-background-color)]",
    footerActionText: "text-copy-13 text-[var(--secondary-text-color)]",
    footerActionLink: "text-label-13 text-[var(--primary-color)] underline-offset-2 hover:underline",
    footerPagesLink: "text-label-12 text-[var(--secondary-text-color)] hover:text-[var(--primary-text-color)]",
    identityPreviewText: "text-copy-14 text-[var(--primary-text-color)]",
    formHeaderTitle: "text-heading-16 text-[var(--primary-text-color)]",
    formHeaderSubtitle: "text-copy-13 text-[var(--secondary-text-color)]",
  },
} as const;
