export const authClerkAppearance = {
  variables: {
    colorPrimary: "var(--ds-blue-600)",
    colorPrimaryForeground: "#ffffff",
    colorDanger: "var(--ds-red-600)",
    colorSuccess: "var(--ds-green-600)",
    colorWarning: "var(--ds-amber-600)",
    colorNeutral: "var(--ds-gray-1000)",
    colorForeground: "var(--ds-gray-1000)",
    colorMutedForeground: "var(--ds-gray-900)",
    colorBackground: "var(--ds-background-100)",
    colorInputForeground: "var(--ds-gray-1000)",
    colorInput: "var(--ds-gray-100)",
    colorBorder: "var(--ds-gray-400)",
    colorRing: "var(--ds-blue-600)",
    colorShadow: "rgba(0, 0, 0, 0)",
    fontFamily: "var(--font-sans), ui-sans-serif, system-ui, sans-serif",
    fontFamilyButtons: "var(--font-sans), ui-sans-serif, system-ui, sans-serif",
    fontSize: "0.875rem",
    borderRadius: "0.5rem",
    spacing: "1rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full",
    card: "w-full rounded-2xl border border-[var(--ds-gray-400)] bg-[var(--ds-background-100)] shadow-none",
    headerTitle: "text-heading-20 text-[var(--ds-gray-1000)]",
    headerSubtitle: "text-copy-14 text-[var(--ds-gray-900)]",
    socialButtonsBlockButton:
      "h-10 rounded-md border border-[var(--ds-gray-400)] bg-[var(--ds-background-100)] text-label-14 text-[var(--ds-gray-1000)] shadow-none transition-colors hover:border-[var(--ds-gray-500)] hover:bg-[var(--ds-gray-100)] focus-visible:ring-2 focus-visible:ring-[var(--ds-blue-600)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--ds-background-100)]",
    socialButtonsBlockButtonText: "text-label-14 text-[var(--ds-gray-1000)]",
    socialButtonsProviderIcon: "text-[var(--ds-gray-900)]",
    dividerText: "text-label-12 uppercase tracking-[0.14em] text-[var(--ds-gray-900)]",
    dividerLine: "bg-[var(--ds-gray-400)]",
    formFieldLabel: "text-label-14 text-[var(--ds-gray-1000)]",
    formFieldInput:
      "h-10 rounded-md border border-[var(--ds-gray-400)] bg-[var(--ds-gray-100)] px-3 text-copy-14 text-[var(--ds-gray-1000)] shadow-none placeholder:text-[var(--ds-gray-900)] focus:border-[var(--ds-blue-600)] focus-visible:ring-2 focus-visible:ring-[var(--ds-blue-600)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--ds-background-100)]",
    formFieldInputShowPasswordButton:
      "text-[var(--ds-gray-900)] transition-colors hover:text-[var(--ds-gray-1000)]",
    formButtonPrimary:
      "h-10 rounded-md bg-[var(--ds-blue-600)] text-label-14 text-white shadow-none transition-colors hover:bg-[var(--ds-blue-700)] focus-visible:ring-2 focus-visible:ring-[var(--ds-blue-600)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--ds-background-100)]",
    formFieldAction: "text-label-13 text-[var(--ds-blue-700)] hover:text-[var(--ds-blue-800)]",
    formFieldErrorText: "text-copy-13 text-[var(--ds-red-600)]",
    formFieldSuccessText: "text-copy-13 text-[var(--ds-green-700)]",
    formResendCodeLink: "text-label-13 text-[var(--ds-blue-700)] hover:text-[var(--ds-blue-800)]",
    otpCodeFieldInput:
      "rounded-md border border-[var(--ds-gray-400)] bg-[var(--ds-gray-100)] text-label-14 text-[var(--ds-gray-1000)] shadow-none focus:border-[var(--ds-blue-600)] focus-visible:ring-2 focus-visible:ring-[var(--ds-blue-600)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--ds-background-100)]",
    footerActionText: "text-copy-13 text-[var(--ds-gray-900)]",
    footerActionLink: "text-label-13 text-[var(--ds-blue-700)] underline-offset-2 hover:underline",
    footerPagesLink: "text-label-12 text-[var(--ds-gray-900)] hover:text-[var(--ds-gray-1000)]",
    identityPreviewText: "text-copy-14 text-[var(--ds-gray-1000)]",
    formHeaderTitle: "text-heading-16 text-[var(--ds-gray-1000)]",
    formHeaderSubtitle: "text-copy-13 text-[var(--ds-gray-900)]",
  },
} as const;
